# Custom Language File for Launcher Customizer

[ejs.app]
title = "One Piece: New Horizon"

[ejs.landing]
mediaGitHubURL = "https://github.com/rayzens1/OPNH-launcher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/vDZNQKPuKU"

[ejs.settings]
sourceGithubLink = "https://github.com/rayzens1/OPNH-launcher"
supportLink = "https://github.com/rayzens1/OPNH-launcher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR ONE PIECE: NEW HORIZON"
welcomeDescription = "One Piece : New Horizon est un serveur Minecraft RP sur le thème du célèbre manga et Anime One Piece, vous y incarnerez un personnage de votre choix, entre Marine, Pirate ou Citoyen, faite votre vie et découvrez les mystères de notre monde. Voyagez d'île en île à la recherche de ressources, de trésors ou de Fruit du Démons afin de devenir plus fort, plus riche ou plus intelligent. Plongez-vous dans une histoire créée pour le serveur dans un univers différent de celui de l'Anime."
welcomeDescCTA = "Vous n'êtes qu'a quelques clique de New Horizon."
